#cloud-config
runcmd:
  - |
    index=1

    # Build list: device size (bytes) device name
    disks=$(lsblk -dn -b -o NAME,SIZE -e 7,11 | grep -E '^vd[b-z]')

    # Sort devices by size (smallest first)
    sorted_disks=$(echo "$disks" | sort -k2 -n | awk '{print $1}')

    for disk in $sorted_disks; do
      device="/dev/$disk"
      fstype=$(blkid -s TYPE -o value "$device" || true)

      # Skip swap partitions
      if [ "$fstype" = "swap" ]; then
        continue
      fi

      label=$(blkid -s LABEL -o value "$device" || true)

      if [ -z "$label" ]; then
        new_label="data$(printf "%02d" $index)"
        mkfs.ext4 -F -L "$new_label" "$device"
        label="$new_label"
        index=$((index + 1))
      else
        # If already labeled ephemeral0, don't increment
        if [[ "$label" != ephemeral* ]]; then
          index=$((index + 1))
        fi
      fi

      mkdir -p "/mnt/$label"
      echo "LABEL=$label /mnt/$label ext4 defaults,nofail 0 2" >> /etc/fstab
      mount "/mnt/$label"
    done
